# Generated by Django 4.0.5 on 2022-07-26 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class_Manager_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(default='Aolad Hossian Sorkar', max_length=50)),
                ('subject_name', models.CharField(choices=[('Bangla', 'Bangla'), ('English', 'English'), ('Math', 'Math'), ('Ict', 'Ict'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('Higher Math', 'Higher Math'), ('Accounting', 'Accounting'), ('Finance Banking', 'Finance Banking'), ('Business Studies', 'Business Studies'), ('Ethics', 'Ethics'), ('History', 'History'), ('Physical Education', 'Physical Education'), ('Agriculture Studies', 'Agriculture Studies'), ('Computer Studies', 'Computer Studies')], default='Physics', max_length=100)),
                ('class_name', models.CharField(choices=[('Six', 'Six'), ('Seven', 'Seven'), ('Eight', 'Eight'), ('Nine', 'Nine'), ('Ten', 'Ten')], max_length=100)),
                ('class_serial', models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('6th', '6th'), ('7th', '7th'), ('8th', '8th'), ('9th', '9th'), ('10th', '10th')], default='1st', max_length=100)),
                ('section_name', models.CharField(choices=[('Rose', 'Rose'), ('Lotus', 'Lotus'), ('Jasmine', 'Jasmine'), ('Orchid', 'Orchid'), ('Tulip', 'Tulip'), ('Science', 'Science'), ('Commerce', 'Commerce'), ('Arts', 'Arts')], default='Jasmine', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='StaffRegisterForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(default='kochu', max_length=100)),
                ('admission_roll', models.IntegerField(default=101)),
                ('email_address', models.EmailField(default='Mahabubhasaan@outlook.com', max_length=200)),
                ('student_class', models.CharField(choices=[('Six', 'Six'), ('Seven', 'Seven'), ('Eight', 'Eight'), ('Nine', 'Nine'), ('Ten', 'Ten')], max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('father_occupation', models.CharField(choices=[('Teacher', 'Teacher'), ('Professor', 'Professor'), ('Businessman', 'Businessman'), ('Sciencist', 'Sciencist'), ('Farmer', 'Farmer'), ('NGO', 'NGO'), ('Banker', 'Banker'), ('Others', 'Others')], default='Teacher', max_length=100)),
                ('mother_occupation', models.CharField(choices=[('Teacher', 'Teacher'), ('Professor', 'Professor'), ('Businessman', 'Businessman'), ('Sciencist', 'Sciencist'), ('Housewife', 'House-wife'), ('NGO', 'NGO'), ('Banker', 'Banker'), ('Others', 'Others')], default='House-wife', max_length=100)),
                ('date_of_birth', models.DateTimeField(max_length=10)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=20)),
                ('course', models.CharField(max_length=100)),
                ('section', models.CharField(choices=[('Rose', 'Rose'), ('Lotus', 'Lotus'), ('Jasmine', 'Jasmine'), ('Orchid', 'Orchid'), ('Tulip', 'Tulip')], default='Jasmine', max_length=100)),
                ('phone_number', models.IntegerField()),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('Others', 'Others')], default='A+', max_length=10)),
                ('religion', models.CharField(choices=[('Islam', 'Islam'), ('Christan', 'Chirstan'), ('Hindu', 'Hindu'), ('Buddho', 'Buddho'), ('Others', 'Others')], default='Islam', max_length=50)),
                ('address', models.TextField(default='House No. 290, Mirpur Section - 12 Dhaka - 1000 ,Bangladesh', max_length=500)),
                ('profile_image', models.ImageField(default='"https://bootdey.com/img/Content/avatar/avatar3.png"', null=True, upload_to='assets')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_name', models.CharField(choices=[('First-Terms', 'First-Terms'), ('Second-Terms', 'Second-Terms'), ('Final-Terms', 'Final-Terms')], max_length=100)),
                ('class_name', models.CharField(choices=[('Six', 'Six'), ('Seven', 'Seven'), ('Eight', 'Eight'), ('Nine', 'Nine'), ('Ten', 'Ten')], max_length=100)),
                ('section_name', models.CharField(choices=[('Rose', 'Rose'), ('Lotus', 'Lotus'), ('Jasmine', 'Jasmine'), ('Orchid', 'Orchid'), ('Tulip', 'Tulip'), ('Science', 'Science'), ('Commerce', 'Commerce'), ('Jasmine', 'Arts')], default='Jasmine', max_length=100)),
                ('start_date', models.DateTimeField(max_length=100)),
                ('end_date', models.DateTimeField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_name', models.CharField(choices=[('First-Terms', 'First-Terms'), ('Second-Terms', 'Second-Terms'), ('Final-Terms', 'Final-Terms')], max_length=100)),
                ('class_name', models.CharField(choices=[('Six', 'Six'), ('Seven', 'Seven'), ('Eight', 'Eight'), ('Nine', 'Nine'), ('Ten', 'Ten')], max_length=100)),
                ('section_name', models.CharField(choices=[('Rose', 'Rose'), ('Lotus', 'Lotus'), ('Jasmine', 'Jasmine'), ('Orchid', 'Orchid'), ('Tulip', 'Tulip'), ('Science', 'Science'), ('Commerce', 'Commerce'), ('Jasmine', 'Arts')], default='Jasmine', max_length=100)),
                ('published_date', models.DateTimeField(max_length=100)),
                ('attached_file', models.FileField(upload_to='assets')),
            ],
        ),
        migrations.CreateModel(
            name='StudentRegisterForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('admission_roll', models.IntegerField(default=101)),
                ('email_address', models.EmailField(default='Mahabubhasaan@outlook.com', max_length=200)),
                ('student_class', models.CharField(choices=[('Six', 'Six'), ('Seven', 'Seven'), ('Eight', 'Eight'), ('Nine', 'Nine'), ('Ten', 'Ten')], max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('father_occupation', models.CharField(choices=[('Teacher', 'Teacher'), ('Professor', 'Professor'), ('Businessman', 'Businessman'), ('Sciencist', 'Sciencist'), ('Farmer', 'Farmer'), ('NGO', 'NGO'), ('Banker', 'Banker'), ('Others', 'Others')], default='Teacher', max_length=100)),
                ('mother_occupation', models.CharField(choices=[('Teacher', 'Teacher'), ('Professor', 'Professor'), ('Businessman', 'Businessman'), ('Sciencist', 'Sciencist'), ('Housewife', 'House-wife'), ('NGO', 'NGO'), ('Banker', 'Banker'), ('Others', 'Others')], default='House-wife', max_length=100)),
                ('date_of_birth', models.DateTimeField(max_length=10)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=20)),
                ('course', models.CharField(max_length=100)),
                ('section', models.CharField(choices=[('Rose', 'Rose'), ('Lotus', 'Lotus'), ('Jasmine', 'Jasmine'), ('Orchid', 'Orchid'), ('Tulip', 'Tulip')], default='Jasmine', max_length=100)),
                ('phone_number', models.IntegerField()),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('Others', 'Others')], default='A+', max_length=10)),
                ('religion', models.CharField(choices=[('Islam', 'Islam'), ('Christan', 'Chirstan'), ('Hindu', 'Hindu'), ('Buddho', 'Buddho'), ('Others', 'Others')], default='Islam', max_length=50)),
                ('address', models.TextField(default='House No. 290, Mirpur Section - 12 Dhaka - 1000 ,Bangladesh', max_length=500)),
                ('profile_image', models.ImageField(null=True, upload_to='assets')),
            ],
        ),
        migrations.CreateModel(
            name='Subject_Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('class_name', models.CharField(max_length=100)),
                ('teacher_name', models.CharField(max_length=100)),
            ],
        ),
    ]
