# Generated by Django 4.0.5 on 2022-07-25 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentregisterform',
            old_name='profile_img',
            new_name='profile_image',
        ),
    ]
