# Generated by Django 4.0.5 on 2022-07-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class_manager_model',
            name='class_serial',
            field=models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('6th', '6th'), ('7th', '7th'), ('8th', '8th'), ('9th', '9th'), ('10th', '10th')], default='1st', max_length=100),
        ),
        migrations.AddField(
            model_name='class_manager_model',
            name='subject_name',
            field=models.CharField(choices=[('Bangla', 'Bangla'), ('English', 'English'), ('Math', 'Math'), ('Ict', 'Ict'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('Higher Math', 'Higher Math'), ('Accounting', 'Accounting'), ('Finance Banking', 'Finance Banking'), ('Business Studies', 'Business Studies'), ('Ethics', 'Ethics'), ('History', 'History'), ('Physical Education', 'Physical Education'), ('Agriculture Studies', 'Agriculture Studies'), ('Computer Studies', 'Computer Studies')], default='Physics', max_length=100),
        ),
        migrations.AddField(
            model_name='class_manager_model',
            name='teacher_name',
            field=models.CharField(default='Aolad Hossian Sorkar', max_length=50),
        ),
        migrations.AlterField(
            model_name='class_manager_model',
            name='section_name',
            field=models.CharField(choices=[('Rose', 'Rose'), ('Lotus', 'Lotus'), ('Jasmine', 'Jasmine'), ('Orchid', 'Orchid'), ('Tulip', 'Tulip'), ('Science', 'Science'), ('Commerce', 'Commerce'), ('Arts', 'Arts')], default='Jasmine', max_length=100),
        ),
    ]
