# Generated by Django 4.0.5 on 2022-07-21 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_studenregisterform_date_of_birth'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudenRegisterForm',
            new_name='StudentRegisterForm',
        ),
    ]
