# Generated by Django 4.0.5 on 2022-07-22 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_studenregisterform_studentregisterform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffregisterform',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('Others', 'Others')], default='A+', max_length=10),
        ),
        migrations.AlterField(
            model_name='staffregisterform',
            name='course',
            field=models.CharField(choices=[('Science', 'Science'), ('Commerce', 'Commerce'), ('Arts', 'Arts'), ('Others', 'Others')], default='Science', max_length=100),
        ),
        migrations.AlterField(
            model_name='staffregisterform',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=20),
        ),
        migrations.AlterField(
            model_name='staffregisterform',
            name='subject_choice',
            field=models.CharField(choices=[('Bangla', 'Bangla'), ('English', 'English'), ('Math', 'Math'), ('ICT', 'ICT'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Higher Math', 'Higher Math'), ('Accounting', 'Accounting'), ('Finance & Banking', 'Finance & Banking'), ('General Science', 'General Science'), ('Bussiness Studies', 'Bussiness Studies'), ('Economics', 'Economics'), ('History', 'History'), ('Ethics', 'Ethics'), ('Others', 'Others')], default='Chemistry', max_length=100),
        ),
    ]
